### ISSUE TITLE
Fixation data does not match gazepoint fixation output

### ISSUE THREAD

**Issue by ashkjones** [TheD2Lab/gazepoint-data-analysis#20] opened 2024-03-12 23:17 UTC
The data in the fixation file output by the refactor program does not match the fixation file output from gazepoint.

This occurs for several places in p1's his fixation file, and probably other participant's fixation data.

Fixation entries from the refactor with SACCADE_MAG = 0 are likely incorrect.

**Edit:** Github won't let me attach the file so search for "p1_fixation_1071" on sharepoint

**Comment by angeloryan** [comment] 2024-03-13 00:25
See commit f0ea996: issue was caused by first cleaning raw gaze data and then filtering by fixations. Order of operations for DataFiltering with DataEntrys will impact fixations and validation algorithms. Issue was fixed by first filtering by fixations, and then running the validation algorithm.

**Closed as completed by angeloryan** 2024-03-13 00:25 UTC
Labels: bug
