### ISSUE TITLE
No AOI -> RPM transition proportion excluding self transitions is incorrectly 1

### ISSUE THREAD

**Issue by ashkjones** [TheD2Lab/gazepoint-data-analysis#27] opened 2024-04-28 03:26 UTC
- "No AOI -> RPM" proportion excluding self transitions is 1 for p10, p11, p21, and more. 
- This is incorrect because it would mean the pilot's gaze only moved from No AOI to the RPM AOI. The proportions should add up to 1 and there are other non-zero transition proportions from No AOI.

**Comment by ashkjones** [comment] 2024-04-29 18:15
Definition of AOI from Dr. Fu 
>Regarding the implementations of the transitions, given n number of AOIs, there will be n*(n-1) pairings, where e.g., given AOIs: A, B, C, D:
  from A to B/C/D, the AB/AC/AD add up to 1;
  from B to A/C/D, the BA/BC/BD add up to 1;
  from C to A/B/D, the CA/CB/CD add up to 1;
  from D to A/B/C, the DA/DB/DC add up to 1.
  
  The current code is calculating from B/C/D to A, the BA/CA/DA add to 1. (Unless we have arrows going in the incorrect direction)
<img width="684" alt="image" src="https://github.com/TheD2Lab/gazepoint-data-analysis/assets/4361319/6c310966-9df5-40f0-9d4e-b1af81ded02d">

**Comment by Immersor-git** [comment] 2024-04-30 22:10
This issue is now fixed. It was caused by a few issues.

First, AOI transitions don't mean that the fixation ID (FPOGID) will be different - I had to switch over to checking if the count (CNT) was subsequent. Second, transitions were checked in the form of B->A + C->A + D->A = 1. This has been switched to be A->B  A->C  A->C = 1. Finally, the AOI transitions were being fed the filtered fixations instead of all of the fixations. This removed a lot of the lines where AOI transitions occurred. All of these have been resolved and pushed to the AOI-pairs-bug-fix branch.

**Closed as completed** 2024-05-01 02:06 UTC
